# Thu Nov 03 2016  11:37:33AM EDT   Thomas Naughton  <naughtont@ornl.gov>

CC=gcc
RM=rm
ECHO=echo

all: hellosleep 

hellosleep:  hellosleep.c
	$(CC) -o hellosleep hellosleep.c 

clean:
	$(RM) -f hellosleep
